## Copyright © 2021, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: "Automate loading data to a data warehouse using a serverless application"
stackDescription: "Automate loading data to a data warehouse using a serverless application."
schemaVersion: 1.1.0
version: "20190404"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - region
  - release
  - ocir_repo_name
  - ADW_database_db_name
  - ADW_database_display_name

- title: Required Configuration
  visible: true  
  variables:
  - compartment_ocid
  - dbpwd-cipher
  - ocir_user_name
  - ocir_user_password
  - show_advanced 

- title: OSS Bucket Optional Configuration
  visible: 
      and:
        - show_advanced
  variables:      
  - input-bucket
  - processed-bucket

- title: Networking Optional Configuration
  visible: 
      and:
        - show_advanced
  variables:      
  - VCN-CIDR
  - fnsubnet-CIDR

- title: Autonomous DB Optional Configuration
  visible: 
      and:
        - show_advanced
  variables:      
  - ADW_database_cpu_core_count
  - ADW_database_data_storage_size_in_tbs
  - ADW_database_db_version
  - ADW_database_license_model
  - ADW_database_freeform_tags
  - ADW_database_defined_tags_value
    
variables:
  
  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    visibile: true
    title: "Compartment"
    description: "Choose compartment where you want to create the solution resources"

  region:
    type: oci:identity:region:name
    required: true
    visibile: true
    title: "Region"
    description: "Choose region where you want to deploy the resources defined by this stack."

  dbpwd-cipher:
    type: password
    required: true
    visibile: true
    title: "ADW Admin Database password"
    description: "ADW Database password for ADMIN user"
    minLength: 12
    maxLength: 30
    pattern: ^[A-Za-z][A-Za-z0-9_#\$]+$ 

  ocir_user_name:
    type: string
    required: true
    visibile: true
    title: "OCIR username"
    description: "Oracle Cloud Infrastructure Registry username (your OCI username)" 

  ocir_user_password:
    type: password
    required: true
    visibile: true
    title: "OCIR user password"
    description: "Oracle Cloud Infrastructure Registry user password (your OCI user authtoken)" 

  # Optional Configuration
  VCN-CIDR:
    type: string
    required: false
    default: "10.0.0.0/16"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR"
    description: "Choose VCN's CIDR block where Fn App will be deployed."

  fnsubnet-CIDR:
    type: string
    required: false
    default: "10.0.2.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Subnet CIDR"
    description: "Choose Public Subnet's CIDR where Fn App will be deployed."  

  ADW_database_cpu_core_count:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "ADW Database CPU Core Count"
    description: "Choose ADW Database CPU Core Count"

  ADW_database_data_storage_size_in_tbs:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "ADW Database Data Storage Size in terabytes"
    description: "Choose ADW Database Data Storage Size in terabytes"

  ADW_database_db_name:
    type: string
    required: false
    default: "ADWDB"
    title: "ADW Database DBNAME"
    description: "Choose ADW Database DBNAME"

  ADW_database_db_version:
    type: enum
    required: false
    default: "19c"
    title: "ADW Database Version"
    description: "Choose ADW Database Version"
    enum:
      - "19c"

  ADW_database_display_name:
    type: string
    required: false
    default: "ADWDB"
    title: "ADW Database Display Name"
    description: "Choose ADW Database Display Name"

  ADW_database_license_model:
    type: enum
    required: false
    default: "LICENSE_INCLUDED"
    title: "ADW Database License Model"
    description: "Choose ADW Database License Model"
    enum:
      - "LICENSE_INCLUDED"
      - "BRING_YOUR_OWN_LICENSE"

  input-bucket:
    type: string
    required: false
    default: "input-bucket"
    title: "Input Bucket Name"
    description: "Choose Bucket Name for InputFiles"
  
  processed-bucket:
    type: string
    required: false
    default: "processed-bucket"
    title: "Processed Bucket Name "
    description: "Choose Bucket Name for ProcessedFiles"


outputs:

  ADW_query_URL_for_JSON_formatted_with_python:
    title: "ADW Query URL for JSON formatted with Python"
    displayText: "ADW Query URL for JSON formatted with Python"
    type: copyableString
    visible: true
